# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'Example.xcworkspace'

target 'ExampleSwift' do
  use_frameworks!
  project 'ExampleSwift/ExampleSwift.xcodeproj'
#  pod 'Masonry', '~> 1.1.0'
 pod 'BjmobAdsSDK', :path => '../'
  # pod 'BjmobAdsSDK', '0.0.31'
  pod 'Bugly'
end

target 'Example' do
  use_frameworks!
  project 'Example/Example.xcodeproj'
  pod 'Masonry', '~> 1.1.0'
#  pod 'BjmobAdsSDK', :path => '../'
#  pod 'BjmobAdsSDK', '0.0.31'
end


post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
